[project]
name = "open-windows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "python-fasthtml>=0.12.14",
    "pytz>=2025.2",
]
